### ISSUE TITLE
Productへのコメント機能を追加する。

### ISSUE THREAD

**Issue by shoheis** [akitojp/products_app#12]
コメントには関連するUser情報とProduct情報(user_idとproduct_id)が入るようにしましょう。

UI/UXは画面遷移図に則った形で進めていきましょう。
新規作成画面は画面遷移図にはないので一旦おまかせいたします、迷った場合はこちらで指示させていただきます！

**Comment by akitojp** [comment]
UI/UXの件承知いたしました。こちらも同時進行で作成いたします!
