### ISSUE TITLE
ProductへのLike機能を追加

### ISSUE THREAD

**Issue by shoheis** [akitojp/products_app#15]
こちらはコメントと似た機能なのでさくっとできてしまうかもしれませんね。

https://github.com/akitojp/products_app/pull/14 ですでにAjax使われていると思いますので同様にAjaxを使って実装してみましょう(ただし詰まるようであれば後回しにしましょう)。

まだ https://github.com/akitojp/products_app/pull/14 をざっくり見た段階ですが、
今回はUnit Testに Rspecを使いますので、ここあたりのファイルはgenerateコマンドで作成しないようにしましょう。
https://github.com/akitojp/products_app/pull/14/files#diff-84faba2f22d82f6f1d5b0bf7d950d576

参考になる記事はこのあたりかと思います。
https://railsguides.jp/generators.html#%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC%E3%82%92%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA%E3%81%99%E3%82%8B

設定は自由なのですが弊社のプロダクトでは
```
orm  active_record
test_framework rspec
view_specs 生成しない
controller_specs 生成する
routing_specs 生成しない
helper_specs 生成しない
request_specs 生成しない
assets 生成しない
helper 生成しない
```
という設定をしています。一旦上記を真似て設定してみましょう。

**Comment by akitojp** [comment]
ありがとうございます! 無駄なファイルを生成しないよう変更いたしました。
