### ISSUE TITLE
細かい変更、バグ修正をする。

### ISSUE THREAD

**Issue by shoheis** [akitojp/products_app#17]
いくつか細かい作業をまとめました。お手すきの際に取り掛かってみてくださいませ。

- [x] testディレクトリの削除
- [x] db/development.sqlite3 の削除
- [x] time_zone の設定。UTCになっているのをJSTにする。
<img width="388" alt="2018-07-10 12 36 45" src="https://user-images.githubusercontent.com/8462476/42488907-107a8174-8443-11e8-8309-a0da49146083.png">

- [x]  deviseのsign_upでnameがバリデーションエラーになるのを修正する。
<img width="515" alt="2018-07-10 12 34 39" src="https://user-images.githubusercontent.com/8462476/42488941-3403fbf2-8443-11e8-8bf6-eec765274c5f.png">

**Comment by akitojp** [comment]
- [ x ] 完了
