### ISSUE TITLE
自分のプロダクトの一覧画面を作成しましょう。

### ISSUE THREAD

**Issue by shoheis** [akitojp/products_app#26]
URLに階層を導入して、自分のプロダクトの一覧ページを作成しましょう。

現状全体のProductをみることができるページは下記のようになっているかと思います。
http://localhost:3000/products

自分のプロダクトだけがみれるページを
http://localhost:3000/manage/products
として作成してみましょう。

ルーティングとそれに合わせてcontrollerを階層化することが必要になってくるかと思います。
ヒント少なめですがまずはやってみましょう。

**Comment by akitojp** [comment]
申請画面一覧
